# ===================================================================
# SERVER CONFIGURATION
# ===================================================================
# Menggunakan port otomatis dari Railway. Jika tidak ada, pakai 8080 (Lokal)
server.port=${PORT:8080}

# ===================================================================
# DATABASE CONFIGURATION (INTERNAL RAILWAY PRIVACY)
# ===================================================================
spring.datasource.driver-class-name=org.postgresql.Driver

# MENGGUNAKAN VALUE DATABASE_URL INTERNAL DARI SCREENSHOT KAMU
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway

# Kredensial Otentikasi Pengguna
spring.datasource.username=postgres
spring.datasource.password=jXFlDntQlCheTBqlodZWMTPwESjVExRV

# ===================================================================
# SPRING DATA JPA & HIBERNATE SETTINGS
# ===================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jackson.serialization.write-dates-as-timestamps=false
